[project]
name = "nouveau-tds"
version = "0.1.0"
description = ""
authors = [
    {name = "Florian"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "holoviews (>=1.21.0,<2.0.0)",
    "h5py (>=3.15.1,<4.0.0)",
    "scikit-learn (>=1.4.0,<2.0.0)",
    "optax (>=0.2.7,<0.3.0)"
]

[tool.poetry]
packages = [{include = "thz_analyzer"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)"
]
